{% set name = "lava-dl" %}
{% set version = "0.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-dl/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 67ff11d5362db7579c375b0e119f954718421b0bdbeede73cc5f77c9391f88e3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }},<3.11
    - matplotlib-base
    - numpy
    - lava
    - pytorch
    - torchvision
    - scipy
    - ninja
    - h5py
    - setuptools
    - opencv

test:
  requires:
    - pytest
    - asteval
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - lava.lib.dl.slayer
    - lava.lib.dl.bootstrap
    - lava.lib.dl.netx
  commands:
    - pytest -k "not test_axonal_delay_ntidigits and not test_mnist and not test_sparse_axonal_delay_ntidigits"

about:
  home: https://github.com/lava-nc/lava-dl
  summary: lava-dl is a library of deep learning tools within Lava that support offline training, online training and inference methods for various Deep Event-Based Networks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
