{% set name = "lava-dl" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-dl/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 27e9164d571e203572c03fa25e0ef70e9cb09ce6cb7fb0234c0d2cca6880495a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - poetry-core
  run:
    - python >=3.8,<3.11
    - matplotlib-base
    - numpy
    - lava
    - pytorch
    - torchvision
    - scipy
    - ninja
    - h5py
    - setuptools

test:
  requires:
    - pytest
    - asteval
  source_files:
    - tests
  imports:
    - lava.lib.dl.slayer
    - lava.lib.dl.bootstrap
    - lava.lib.dl.netx
  commands:
    - pytest -k "not test_axonal_delay_ntidigits and not test_mnist"

about:
  home: https://github.com/lava-nc/lava-dl
  summary: lava-dl is a library of deep learning tools within Lava that support offline training, online training and inference methods for various Deep Event-Based Networks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
